export default {
  PROFILE: {
    GET_PROFILE: 'GET_PROFILE',
    RESET: 'PROFILE_RESET',
  },
  PROFILE_FORM: {
    SUBMIT: 'SUBMIT',
    RESET: 'PROFILE_FORM_RESET',
  },
  LOGIN_FORM: {
    SIGN_UP: 'SIGN_UP',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    RESET: 'LOGIN_FORM_RESET',
  },
  EVALUATION_LOGIN: {
    PARENT_LOG_IN: 'PARENT_LOG_IN',
    SIGN_UP: 'WALLET_SIGN_UP',
    CHILD_LOG_IN: 'CHILD_LOG_IN',
    LOG_OUT: 'WALLET_LOG_OUT',
    RESET: 'EVALUATION_LOGIN_RESET',
  },
  WORKSPACE: {
    DEPLOY_WORKSPACE: 'DEPLOY_WORKSPACE',
    GET_WORKSPACE: 'GET_WORKSPACE',
    RESET: 'WORKSPACE_RESET',
  },
  EVALUATION: {
    VOTE: 'VOTE',
  },
  AUDIT: {
    GET_REVIEW_RESULT: 'GET_REVIEW_RESULT',
  },
};
